########## This file is automatically generated. Any changes to this file will be lost. ##########
########## If you have your own constraints tcl file, please add it to the project ##########
########## by using the "Set custom config file" constraint in the HLS Constraints dialog. ##########
source $env(LEGUP_ROOT_DIR)/examples/legup.tcl
set_project CycloneIV EP4CE22F17C6N hw_only
function_pipeline FIRFilterStreaming
set_custom_top_level_module FIRFilterStreaming
set_synthesis_top_module FIRFilterStreaming_top
set_operation_latency multiply 1
set_parameter CLOCK_PERIOD 10
set_custom_test_bench_module streaming_tb
set_custom_test_bench_file streaming_tb.v
